language: ruby
rvm:
  - "2.5.1"
services: postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rspec spec
